import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/ui/sidebar";
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarSeparator,
  MenubarShortcut,
  MenubarTrigger,
} from "@/components/ui/menubar";
import { ArrowUpRight } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex",
          inter.className,
          { "debug-screens": process.env.NODE_ENV === "development" }
        )}
      >
        {/* Sidebar */}
        <div className="fixed top-1/2 left-0 transform -translate-y-1/2 p-2">
          <Sidebar />
        </div>

        {/* Menubar */}
        <div className="absolute top-0 left-1/2 transform -translate-x-1/2 p-4 mb-8">
          <Menubar>
            <MenubarMenu>
              <MenubarTrigger>
                <ArrowUpRight />
              </MenubarTrigger>
              <MenubarTrigger>Home</MenubarTrigger>
              <MenubarTrigger>About Us</MenubarTrigger>
              <MenubarTrigger>Support</MenubarTrigger>
            </MenubarMenu>
          </Menubar>
        </div>

        {/* main page */}
        <div className="p-8 pl-20 w-full" style={{ paddingTop: "72px" }}>
          {children}
        </div>
      </body>
    </html>
  );
}
