name: Build and Start
on:
  push:
    branches:
      - main

jobs:
  build-and-start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: |
          npm run dev
          echo "Dev build completed successfully"

      - name: Stop the server
        run: |
          kill $(cat server.pid)
          echo "Server stopped successfully"
